### ISSUE TITLE
LuckyBlock break issue

### ISSUE THREAD

**Issue by poma123** [TheBusyBiscuit/luckyblocks-sf#14]
## Description (Required)

It just doesn't give the surprise, it drops a CSCoreLib's Head instead.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=QdVxl-nKY4s
![image](https://user-images.githubusercontent.com/25465545/74595433-84d6fe00-5041-11ea-86b7-30c89a8953b7.png)

## Expected behavior (Required)

The lucky block should give the random surprise.

## Server Log / Error Report

There were no errors in console.

## Environment (Required)

![image](https://user-images.githubusercontent.com/25465545/74595477-f57e1a80-5041-11ea-98a2-c793bc3c7f9f.png)

**Comment by AccioAce** [comment]
Yep, this is the issue that luckyblock is having.
