### ISSUE TITLE
Lucky Blocks disappear explosion

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/luckyblocks-sf#21]
## Description (Required)

Lucky Blocks disappear explosion

## Steps to reproduce the Issue (Required)

1. Place Lucky Block next to TNT
2. Activate the TNT
3. Lucky block disappear

## Expected behavior (Required)

Lucky block no disappear

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version:  88 (git 6a39a9e7)
 - Slimefun Version:  584 (git 9af90830)
 - LuckyBlocks Version: 25 (git c24d0770)

**Comment by TheBusyBiscuit** [comment]
Might be fixed by #20 too

**Comment by andris155** [comment]
@TheBusyBiscuit 
This update don't fix this bug.
https://www.youtube.com/watch?v=ci9H-po0Mgs
