### ISSUE TITLE
LuckyBlock dupe glitch

### ISSUE THREAD

**Issue by ryan-bing** [TheBusyBiscuit/luckyblocks-sf#22]
## Description (Required)
When a player crafts a new LuckyBlock and place it and break it with their hand, it causes the surprise to happen, but also doesn't remove the LuckyBlock, resulting in infinite rewards.

## Steps to reproduce the Issue (Required)
1. Craft LuckyBlock
2. Place LuckyBlock
3. Break LuckyBlock with hand

## Expected behavior (Required)
Surprise should happen and block should be removed. Instead, block is dropped resulting in infinite LuckyBlocks.

## Server Log / Error Report
No errors appear in the console.

## Environment (Required)
16.07 16:55:56 [Server] INFO Paper v1_16_R1
16.07 16:55:56 [Server] INFO CS-CoreLib vDEV - 88 (git 6a39a9e7)
16.07 16:55:56 [Server] INFO Slimefun vDEV - 584 (git 9af90830)
16.07 16:55:56 [Server] INFO Installed Addons (5)
16.07 16:55:56 [Server] INFO DyedBackpacks vDEV - 9 (git c42435c1)
16.07 16:55:56 [Server] INFO ExtraHeads vDEV - 17 (git 6c77b605)
16.07 16:55:56 [Server] INFO ExtraGear vDEV - 10 (git 892256da)
16.07 16:55:56 [Server] INFO MegaSlime v1.2
16.07 16:55:56 [Server] INFO ExoticGarden vDEV - 55 (git cce4c0f4)

**Comment by j19mes** [comment]
Yeah having this issue as well.
