### ISSUE TITLE
[Feature request] Support for generator plugins

### ISSUE THREAD

**Issue by Volgeop** [TheBusyBiscuit/luckyblocks-sf#24]
Hi, I wanna ask for support for these two plugins - https://www.spigotmc.org/resources/chunkmaster.71351/ and https://www.spigotmc.org/threads/regionerator.92022.

First one to let lucky blocks be pregenerated in the world automatically with chunkmaster generate <world> command.

Second one for automatically pregenerating lucky blocks in new chunks, when chunk is pregenerated.

**Comment by TheBusyBiscuit** [comment]
The bug tracker is only for bugs. You can post suggestions on discord.
