### ISSUE TITLE
Weird villager hashtags?

### ISSUE THREAD

**Issue by Volgeop** [TheBusyBiscuit/luckyblocks-sf#26]
## Description (Required)

Hi, my villagers have weird hashtags when they're summoned from Lucky (or unlucky) block.

## Steps to reproduce the Issue (Required)
https://imgur.com/52YZf0X just destroyed lucky block, don't know if this is lucky or unlucky

## Expected behavior (Required)

They shouldn't have this # hashtag with number?

## Environment (Required)

 - Minecraft Version: 1.16.1
 - CS-CoreLib Version: 88
 - Slimefun Version: 631
 - LuckyBlocks Version: 28

**Comment by TheBusyBiscuit** [comment]
That is intended... It is a reference.

The entire point of lucky blocks is to be random and weird...  You are the first person to question this in 6 years.

**Comment by Volgeop** [comment]
Lol, I though it's bug 😅
