### ISSUE TITLE
duplication

### ISSUE THREAD

**Issue by 100petr** [TheBusyBiscuit/luckyblocks-sf#33]
## Description (Required)

The lucky block is not destroyed and droped with a items.

## Steps to reproduce the Issue (Required)

Destroy the block next to the lucky block with explosive pickaxe
Video: https://youtu.be/sIw_1JSpxlc

## Expected behavior (Required)

The lucky block will be destroyed

## Server Log / Error Report

No error, https://pastebin.com/7HdQhYAm

## Environment (Required)

![image](https://user-images.githubusercontent.com/29830635/98539397-89f17280-228c-11eb-8650-d7e7efeb1580.png)

**Comment by bobhenl** [comment]
I can agree...

**Comment by bobhenl** [comment]
I think that this bug should be really fixed as soon as possible

**Comment by 100petr** [comment]
ChestTerminal and PrivateStorage are already fixed, luckyblocks still is not.

**Comment by 100petr** [comment]
ChestTerminal and PrivateStorage are already fixed, LuckyBlocky still is not.

**Comment by TheBusyBiscuit** [comment]
This dupe should be fixed in the latest version of LuckyBlocks.
